// Catalogue brands (docs/master-catalogue Phase 19): the manufacturers a
// customer can pick on a product-linked booking, and the appliances each is
// offered for. Every brand starts with the platform's 12-month manufacturer
// warranty — change it per brand in Super Admin → Categories & Brands.
// Listed most-widely-offered first; that order is the picker order.
export const CATALOGUE_BRAND_SEED = [
  { name: 'LG', categories: ['AC', 'Washing Machine', 'Refrigerator', 'TV', 'Microwave'] },
  { name: 'Panasonic', categories: ['AC', 'Washing Machine', 'Refrigerator', 'TV', 'Microwave'] },
  { name: 'Samsung', categories: ['AC', 'Washing Machine', 'Refrigerator', 'TV', 'Microwave'] },
  { name: 'Whirlpool', categories: ['AC', 'Washing Machine', 'Refrigerator', 'Microwave', 'Chimney'] },
  { name: 'Bosch', categories: ['Washing Machine', 'Refrigerator', 'Microwave', 'Chimney'] },
  { name: 'Voltas', categories: ['AC', 'Washing Machine', 'Refrigerator', 'Air Cooler'] },
  { name: 'Bajaj', categories: ['Geyser', 'Microwave', 'Air Cooler'] },
  { name: 'Godrej', categories: ['Washing Machine', 'Refrigerator', 'Microwave'] },
  { name: 'Haier', categories: ['Washing Machine', 'Refrigerator', 'TV'] },
  { name: 'Havells', categories: ['RO Water Purifier', 'Geyser', 'Air Cooler'] },
  { name: 'IFB', categories: ['Washing Machine', 'Microwave', 'Chimney'] },
  { name: 'AO Smith', categories: ['RO Water Purifier', 'Geyser'] },
  { name: 'Blue Star', categories: ['AC', 'RO Water Purifier'] },
  { name: 'Crompton', categories: ['Geyser', 'Air Cooler'] },
  { name: 'Hindware', categories: ['Chimney', 'Air Cooler'] },
  { name: 'Hitachi', categories: ['AC', 'Refrigerator'] },
  { name: 'Kenstar', categories: ['Geyser', 'Air Cooler'] },
  { name: 'Orient', categories: ['Geyser', 'Air Cooler'] },
  { name: 'Philips', categories: ['TV', 'Microwave'] },
  { name: 'Siemens', categories: ['Washing Machine', 'Chimney'] },
  { name: 'Usha', categories: ['Geyser', 'Air Cooler'] },
  { name: 'Aquaguard', categories: ['RO Water Purifier'] },
  { name: 'Carrier', categories: ['AC'] },
  { name: 'Cello', categories: ['Air Cooler'] },
  { name: 'Daikin', categories: ['AC'] },
  { name: 'Elica', categories: ['Chimney'] },
  { name: 'Eureka Forbes', categories: ['RO Water Purifier'] },
  { name: 'Faber', categories: ['Chimney'] },
  { name: 'Glen', categories: ['Chimney'] },
  { name: 'Hisense', categories: ['TV'] },
  { name: 'HUL', categories: ['RO Water Purifier'] },
  { name: 'Kaff', categories: ['Chimney'] },
  { name: 'Kent', categories: ['RO Water Purifier'] },
  { name: 'Liebherr', categories: ['Refrigerator'] },
  { name: 'Livpure', categories: ['RO Water Purifier'] },
  { name: 'Lloyd', categories: ['AC'] },
  { name: 'Luminous', categories: ['RO Water Purifier'] },
  { name: 'Mi', categories: ['TV'] },
  { name: 'Morphy Richards', categories: ['Microwave'] },
  { name: 'O General', categories: ['AC'] },
  { name: 'OnePlus', categories: ['TV'] },
  { name: 'Pureit', categories: ['RO Water Purifier'] },
  { name: 'Racold', categories: ['Geyser'] },
  { name: 'Sony', categories: ['TV'] },
  { name: 'Sunflame', categories: ['Chimney'] },
  { name: 'Symphony', categories: ['Air Cooler'] },
  { name: 'TCL', categories: ['TV'] },
  { name: 'V-Guard', categories: ['Geyser'] },
  { name: 'Venus', categories: ['Geyser'] },
  { name: 'VU', categories: ['TV'] },
].map((brand, index) => ({ warrantyMonths: 12, sortOrder: index + 1, ...brand }));
