// Mirrors frontend/src/data/bookingCatalog.js's BOOKING_CATALOG so the seeded
// backend catalog is a drop-in replacement once the frontend is wired to real
// APIs (roadmap Phase 13) — same categories, product types, services, prices.
export const CATALOG_SEED = [
  {
    key: 'AC',
    name: 'AC',
    color: '#0D47A1',
    lightBg: '#EAF4FF',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    brands: ['Voltas', 'LG', 'Samsung', 'Daikin', 'Whirlpool', 'Lloyd', 'Panasonic', 'Blue Star', 'Hitachi', 'Carrier', 'O General'],
    whyBrandPoints: [
      'Technicians carry brand-specific gas & parts',
      'AC model-specific calibration & settings',
      'Correct refrigerant type (R22 vs R410A)',
    ],
    productTypes: [
      { slug: 'split', name: 'Split AC', icon: '❄️', desc: '1 ton · 1.5 ton · 2 ton' },
      { slug: 'window', name: 'Window AC', icon: '🪟', desc: 'Single wall-mount unit' },
      { slug: 'cassette', name: 'Cassette AC', icon: '⬛', desc: 'Ceiling mounted / 4-way' },
      { slug: 'tower', name: 'Tower AC', icon: '🏛️', desc: 'Floor standing unit' },
      { slug: 'portable', name: 'Portable AC', icon: '🔄', desc: 'Movable, no installation' },
    ],
    services: [
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New AC fitting & setup', price: 499 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Fix breakdowns & issues', price: 299 },
      { slug: 'gas_refilling', name: 'Gas Refilling', icon: '💨', desc: 'Refrigerant top-up', price: 799 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Preventive check & tune-up', price: 349 },
      { slug: 'deep_cleaning', name: 'Deep Cleaning', icon: '✨', desc: 'Foam-jet wash & coil clean', price: 649 },
      { slug: 'uninstall', name: 'Uninstallation', icon: '📤', desc: 'Safe removal & packing', price: 299 },
    ],
  },
  {
    key: 'Washing Machine',
    name: 'Washing Machine',
    color: '#1565C0',
    lightBg: '#E3F2FD',
    categoryNote: 'Prices are indicative. Exact charges are confirmed after inspection by the technician.',
    brands: ['LG', 'Samsung', 'Whirlpool', 'IFB', 'Bosch', 'Haier', 'Godrej', 'Panasonic', 'Voltas', 'Siemens'],
    whyBrandPoints: [
      'Brand-specific PCB & motor spare parts stocked',
      'Correct drum belt & bearing specifications',
      'Model-specific error code diagnosis',
    ],
    productTypes: [
      { slug: 'front_load', name: 'Front Load', icon: '🔄', desc: 'Auto, drum in front' },
      { slug: 'top_load', name: 'Top Load', icon: '⬆️', desc: 'Auto, drum on top' },
      { slug: 'semi_auto', name: 'Semi Automatic', icon: '⚙️', desc: 'Manual water fill' },
    ],
    services: [
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Fix spin, drain & motor issues', price: 399 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New machine setup & demo', price: 299 },
      { slug: 'drum_cleaning', name: 'Drum Cleaning', icon: '✨', desc: 'Deep drum & tub sanitisation', price: 499 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Preventive service & check', price: 349 },
      { slug: 'uninstall', name: 'Uninstallation', icon: '📤', desc: 'Safe removal & packing', price: 199 },
    ],
  },
  {
    key: 'Refrigerator',
    name: 'Refrigerator',
    color: '#4527A0',
    lightBg: '#EDE7F6',
    categoryNote: 'Cooling issues may need gas refilling — exact diagnosis done by the technician on-site.',
    brands: ['LG', 'Samsung', 'Whirlpool', 'Godrej', 'Haier', 'Panasonic', 'Bosch', 'Voltas', 'Hitachi', 'Liebherr'],
    whyBrandPoints: [
      'Brand-specific compressor & thermostat parts',
      'Correct refrigerant type (R600a vs R134a)',
      'Model-specific PCB & sensor calibration',
    ],
    productTypes: [
      { slug: 'single_door', name: 'Single Door', icon: '🚪', desc: '100 L – 260 L capacity' },
      { slug: 'double_door', name: 'Double Door', icon: '🚪🚪', desc: '260 L – 450 L capacity' },
      { slug: 'side_by_side', name: 'Side By Side', icon: '◀️▶️', desc: '500 L+ premium model' },
      { slug: 'convertible', name: 'Convertible', icon: '🔁', desc: 'Fridge-freezer switching' },
      { slug: 'french_door', name: 'French Door', icon: '🏠', desc: 'Multi-door premium' },
    ],
    services: [
      { slug: 'cooling_issue', name: 'Cooling Issue', icon: '🌡️', desc: 'Not cooling / over-freezing fix', price: 449 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'Setup, levelling & demo', price: 299 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'General repairs & part fix', price: 499 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Coil clean & annual check', price: 349 },
      { slug: 'gas_refilling', name: 'Gas Refilling', icon: '💨', desc: 'Refrigerant refill', price: 899 },
    ],
  },
  {
    key: 'TV',
    name: 'TV',
    color: '#B71C1C',
    lightBg: '#FFEBEE',
    categoryNote: 'Panel repairs depend on part availability. Technician will confirm before proceeding.',
    brands: ['LG', 'Samsung', 'Sony', 'Panasonic', 'Mi', 'OnePlus', 'TCL', 'Haier', 'VU', 'Philips', 'Hisense'],
    whyBrandPoints: [
      'Brand-specific display panels & backlights stocked',
      'Firmware & software issues diagnosed correctly',
      'Correct T-Con board & power supply components',
    ],
    productTypes: [
      { slug: 'led', name: 'LED TV', icon: '📺', desc: 'Standard LED/LCD flat screen' },
      { slug: 'oled', name: 'OLED TV', icon: '🖥️', desc: 'Organic LED, deep blacks' },
      { slug: 'qled', name: 'QLED TV', icon: '💎', desc: 'Quantum dot premium display' },
      { slug: 'smart_tv', name: 'Smart TV', icon: '📱', desc: 'Android / Tizen / WebOS' },
    ],
    services: [
      { slug: 'wall_mount', name: 'Wall Mount Installation', icon: '🔩', desc: 'TV mounting & cable management', price: 299 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'No display, flickering, no sound', price: 349 },
      { slug: 'display_issue', name: 'Display Issue', icon: '🖥️', desc: 'Screen lines, colour fix', price: 599 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Deep clean & port check', price: 249 },
      { slug: 'panel_repair', name: 'Panel Replacement', icon: '🔄', desc: 'Screen panel change', price: 1499 },
    ],
  },
  {
    key: 'RO Water Purifier',
    name: 'RO Water Purifier',
    color: '#00695C',
    lightBg: '#E0F2F1',
    categoryNote: 'Filter replacement intervals depend on your water quality (usually every 6–12 months).',
    brands: ['Kent', 'Eureka Forbes', 'Aquaguard', 'Pureit', 'Blue Star', 'AO Smith', 'Livpure', 'HUL', 'Luminous', 'Havells'],
    whyBrandPoints: [
      'Brand-specific filter cartridges & membranes available',
      'Correct TDS calibration per model specs',
      'Genuine UV bulbs & RO membranes used',
    ],
    productTypes: [
      { slug: 'ro', name: 'RO', icon: '💧', desc: 'Reverse osmosis purifier' },
      { slug: 'uv', name: 'UV', icon: '☀️', desc: 'Ultraviolet purifier' },
      { slug: 'uf', name: 'UF', icon: '🌊', desc: 'Ultrafiltration purifier' },
      { slug: 'ro_uv', name: 'RO + UV', icon: '💠', desc: 'Combined RO & UV system' },
    ],
    services: [
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New purifier setup & fitting', price: 399 },
      { slug: 'filter_replacement', name: 'Filter Replacement', icon: '🔄', desc: 'Replace complete filter set', price: 799 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'No water / leakage fix', price: 349 },
      { slug: 'amc_service', name: 'AMC Service', icon: '📋', desc: 'Annual maintenance contract', price: 999 },
      { slug: 'membrane_change', name: 'Membrane Change', icon: '♻️', desc: 'RO membrane replacement', price: 849 },
    ],
  },
  {
    key: 'Geyser',
    name: 'Geyser',
    color: '#E65100',
    lightBg: '#FFF3E0',
    categoryNote: 'Regular tank flushing every 2 years extends geyser life significantly.',
    brands: ['Havells', 'AO Smith', 'Racold', 'Bajaj', 'V-Guard', 'Venus', 'Kenstar', 'Usha', 'Orient', 'Crompton'],
    whyBrandPoints: [
      'Brand-specific heating elements & thermostats available',
      'Correct wattage element for your tank capacity',
      'Safety pressure valve check per brand specs',
    ],
    productTypes: [
      { slug: 'storage', name: 'Storage Geyser', icon: '🛢️', desc: '10 L · 15 L · 25 L tank' },
      { slug: 'instant', name: 'Instant Geyser', icon: '⚡', desc: 'Tankless, rapid heating' },
      { slug: 'solar', name: 'Solar Heater', icon: '☀️', desc: 'Solar panel water heater' },
    ],
    services: [
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Heating element & thermostat fix', price: 299 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New geyser fitting & safety check', price: 399 },
      { slug: 'service_flush', name: 'Service & Flush', icon: '✨', desc: 'Tank descaling & flushing', price: 349 },
      { slug: 'element_replacement', name: 'Element Replacement', icon: '🔌', desc: 'Heating rod change', price: 499 },
      { slug: 'anode_replacement', name: 'Anode Rod Change', icon: '🔩', desc: 'Anti-corrosion rod replacement', price: 299 },
    ],
  },
  {
    key: 'Microwave',
    name: 'Microwave',
    color: '#37474F',
    lightBg: '#ECEFF1',
    categoryNote: 'Never use metal containers inside. Technician will inspect for any magnetron damage.',
    brands: ['LG', 'Samsung', 'IFB', 'Morphy Richards', 'Bajaj', 'Panasonic', 'Godrej', 'Whirlpool', 'Philips', 'Bosch'],
    whyBrandPoints: [
      'Brand-specific magnetron & waveguide cover parts',
      'Correct turntable motor & coupler replacements',
      'Model-specific control panel & keypad parts',
    ],
    productTypes: [
      { slug: 'solo', name: 'Solo Microwave', icon: '📡', desc: 'Basic reheating only' },
      { slug: 'grill', name: 'Grill Microwave', icon: '🔥', desc: 'Heating + grilling mode' },
      { slug: 'convection', name: 'Convection', icon: '🌀', desc: 'Baking, roasting & grilling' },
      { slug: 'otg', name: 'OTG', icon: '🍞', desc: 'Oven toaster griller' },
    ],
    services: [
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Not heating, sparking or dead', price: 349 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'Setup, demo & safety check', price: 199 },
      { slug: 'deep_cleaning', name: 'Deep Cleaning', icon: '✨', desc: 'Interior deodorisation & clean', price: 249 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Annual check & magnetron test', price: 299 },
    ],
  },
  {
    key: 'Chimney',
    name: 'Chimney',
    color: '#212121',
    lightBg: '#F5F5F5',
    categoryNote: 'Chimney should be deep-cleaned every 3–6 months for optimal suction performance.',
    brands: ['Faber', 'Elica', 'Glen', 'Hindware', 'Kaff', 'Sunflame', 'Bosch', 'IFB', 'Siemens', 'Whirlpool'],
    whyBrandPoints: [
      'Brand-specific motor & oil collector parts available',
      'Correct ducting adaptor & pipe fittings used',
      'Auto-clean motor serviced per brand manual',
    ],
    productTypes: [
      { slug: 'baffle', name: 'Baffle Filter', icon: '🌀', desc: 'Curved aluminium mesh' },
      { slug: 'cassette', name: 'Cassette Filter', icon: '📦', desc: 'Easy-clean cartridge' },
      { slug: 'auto', name: 'Auto-Clean', icon: '✨', desc: 'Self-cleaning oil collector' },
      { slug: 'filterless', name: 'Filterless', icon: '🔆', desc: 'No filter, centrifugal tech' },
    ],
    services: [
      { slug: 'deep_cleaning', name: 'Deep Cleaning', icon: '✨', desc: 'Filter, motor & oil collector clean', price: 399 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Motor, suction & button fix', price: 349 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New chimney mounting & ducting', price: 499 },
      { slug: 'filter_replace', name: 'Filter Replacement', icon: '🔄', desc: 'Baffle / mesh / cassette change', price: 299 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Annual service & suction test', price: 349 },
    ],
  },
  {
    key: 'Air Cooler',
    name: 'Air Cooler',
    color: '#1565C0',
    lightBg: '#E3F2FD',
    categoryNote: 'Replace cooling pads every season for best cooling efficiency.',
    brands: ['Symphony', 'Bajaj', 'Orient', 'Kenstar', 'Crompton', 'Hindware', 'Usha', 'Havells', 'Voltas', 'Cello'],
    whyBrandPoints: [
      'Brand-specific pump & motor replacements available',
      'Correct cooling pad type (honeycomb vs wood wool)',
      'Float valve & water distributor parts matched to model',
    ],
    productTypes: [
      { slug: 'desert', name: 'Desert Cooler', icon: '🏜️', desc: 'Large, high-capacity tank' },
      { slug: 'personal', name: 'Personal Cooler', icon: '👤', desc: 'Compact & portable' },
      { slug: 'tower', name: 'Tower Cooler', icon: '🏛️', desc: 'Tall, 360° airflow' },
      { slug: 'window', name: 'Window Cooler', icon: '🪟', desc: 'Window-mounted unit' },
    ],
    services: [
      { slug: 'service_clean', name: 'Service & Clean', icon: '✨', desc: 'Pad, pump & tank clean', price: 249 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Motor, pump & fan fix', price: 299 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'Setup & positioning', price: 199 },
      { slug: 'pad_change', name: 'Cooling Pad Change', icon: '🧽', desc: 'Replace honeycomb/wood pads', price: 349 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Pre-summer full check', price: 299 },
    ],
  },
];
