// Mirrors frontend/src/data/bookingCatalog.js's BOOKING_CATALOG so the seeded
// backend catalog is a drop-in replacement once the frontend is wired to real
// APIs (roadmap Phase 13) — same categories, product types, services, prices.
export const CATALOG_SEED = [
  {
    key: 'AC',
    name: 'AC',
    color: '#0D47A1',
    lightBg: '#EAF4FF',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Prices shown are indicative. The serviceProvider will confirm exact charges after inspection.',
    brands: ['Voltas', 'LG', 'Samsung', 'Daikin', 'Whirlpool', 'Lloyd', 'Panasonic', 'Blue Star', 'Hitachi', 'Carrier', 'O General'],
    whyBrandPoints: [
      'ServiceProviders carry brand-specific gas & parts',
      'AC model-specific calibration & settings',
      'Correct refrigerant type (R22 vs R410A)',
    ],
    productTypes: [
      { slug: 'split', name: 'Split AC', icon: '❄️', desc: '1 ton · 1.5 ton · 2 ton' },
      { slug: 'window', name: 'Window AC', icon: '🪟', desc: 'Single wall-mount unit' },
      { slug: 'cassette', name: 'Cassette AC', icon: '⬛', desc: 'Ceiling mounted / 4-way' },
      { slug: 'tower', name: 'Tower AC', icon: '🏛️', desc: 'Floor standing unit' },
      { slug: 'portable', name: 'Portable AC', icon: '🔄', desc: 'Movable, no installation' },
    ],
    services: [
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New AC fitting & setup', price: 499 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Fix breakdowns & issues', price: 299 },
      { slug: 'gas_refilling', name: 'Gas Refilling', icon: '💨', desc: 'Refrigerant top-up', price: 799 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Preventive check & tune-up', price: 349 },
      { slug: 'deep_cleaning', name: 'Deep Cleaning', icon: '✨', desc: 'Foam-jet wash & coil clean', price: 649 },
      { slug: 'uninstall', name: 'Uninstallation', icon: '📤', desc: 'Safe removal & packing', price: 299 },
    ],
  },
  {
    key: 'Washing Machine',
    name: 'Washing Machine',
    color: '#1565C0',
    lightBg: '#E3F2FD',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Prices are indicative. Exact charges are confirmed after inspection by the serviceProvider.',
    brands: ['LG', 'Samsung', 'Whirlpool', 'IFB', 'Bosch', 'Haier', 'Godrej', 'Panasonic', 'Voltas', 'Siemens'],
    whyBrandPoints: [
      'Brand-specific PCB & motor spare parts stocked',
      'Correct drum belt & bearing specifications',
      'Model-specific error code diagnosis',
    ],
    productTypes: [
      { slug: 'front_load', name: 'Front Load', icon: '🔄', desc: 'Auto, drum in front' },
      { slug: 'top_load', name: 'Top Load', icon: '⬆️', desc: 'Auto, drum on top' },
      { slug: 'semi_auto', name: 'Semi Automatic', icon: '⚙️', desc: 'Manual water fill' },
    ],
    services: [
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Fix spin, drain & motor issues', price: 399 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New machine setup & demo', price: 299 },
      { slug: 'drum_cleaning', name: 'Drum Cleaning', icon: '✨', desc: 'Deep drum & tub sanitisation', price: 499 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Preventive service & check', price: 349 },
      { slug: 'uninstall', name: 'Uninstallation', icon: '📤', desc: 'Safe removal & packing', price: 199 },
    ],
  },
  {
    key: 'Refrigerator',
    name: 'Refrigerator',
    color: '#4527A0',
    lightBg: '#EDE7F6',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Cooling issues may need gas refilling — exact diagnosis done by the serviceProvider on-site.',
    brands: ['LG', 'Samsung', 'Whirlpool', 'Godrej', 'Haier', 'Panasonic', 'Bosch', 'Voltas', 'Hitachi', 'Liebherr'],
    whyBrandPoints: [
      'Brand-specific compressor & thermostat parts',
      'Correct refrigerant type (R600a vs R134a)',
      'Model-specific PCB & sensor calibration',
    ],
    productTypes: [
      { slug: 'single_door', name: 'Single Door', icon: '🚪', desc: '100 L – 260 L capacity' },
      { slug: 'double_door', name: 'Double Door', icon: '🚪🚪', desc: '260 L – 450 L capacity' },
      { slug: 'side_by_side', name: 'Side By Side', icon: '◀️▶️', desc: '500 L+ premium model' },
      { slug: 'convertible', name: 'Convertible', icon: '🔁', desc: 'Fridge-freezer switching' },
      { slug: 'french_door', name: 'French Door', icon: '🏠', desc: 'Multi-door premium' },
    ],
    services: [
      { slug: 'cooling_issue', name: 'Cooling Issue', icon: '🌡️', desc: 'Not cooling / over-freezing fix', price: 449 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'Setup, levelling & demo', price: 299 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'General repairs & part fix', price: 499 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Coil clean & annual check', price: 349 },
      { slug: 'gas_refilling', name: 'Gas Refilling', icon: '💨', desc: 'Refrigerant refill', price: 899 },
    ],
  },
  {
    key: 'TV',
    name: 'TV',
    color: '#B71C1C',
    lightBg: '#FFEBEE',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Panel repairs depend on part availability. ServiceProvider will confirm before proceeding.',
    brands: ['LG', 'Samsung', 'Sony', 'Panasonic', 'Mi', 'OnePlus', 'TCL', 'Haier', 'VU', 'Philips', 'Hisense'],
    whyBrandPoints: [
      'Brand-specific display panels & backlights stocked',
      'Firmware & software issues diagnosed correctly',
      'Correct T-Con board & power supply components',
    ],
    productTypes: [
      { slug: 'led', name: 'LED TV', icon: '📺', desc: 'Standard LED/LCD flat screen' },
      { slug: 'oled', name: 'OLED TV', icon: '🖥️', desc: 'Organic LED, deep blacks' },
      { slug: 'qled', name: 'QLED TV', icon: '💎', desc: 'Quantum dot premium display' },
      { slug: 'smart_tv', name: 'Smart TV', icon: '📱', desc: 'Android / Tizen / WebOS' },
    ],
    services: [
      { slug: 'wall_mount', name: 'Wall Mount Installation', icon: '🔩', desc: 'TV mounting & cable management', price: 299 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'No display, flickering, no sound', price: 349 },
      { slug: 'display_issue', name: 'Display Issue', icon: '🖥️', desc: 'Screen lines, colour fix', price: 599 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Deep clean & port check', price: 249 },
      { slug: 'panel_repair', name: 'Panel Replacement', icon: '🔄', desc: 'Screen panel change', price: 1499 },
    ],
  },
  {
    key: 'RO Water Purifier',
    name: 'RO Water Purifier',
    color: '#00695C',
    lightBg: '#E0F2F1',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Filter replacement intervals depend on your water quality (usually every 6–12 months).',
    brands: ['Kent', 'Eureka Forbes', 'Aquaguard', 'Pureit', 'Blue Star', 'AO Smith', 'Livpure', 'HUL', 'Luminous', 'Havells'],
    whyBrandPoints: [
      'Brand-specific filter cartridges & membranes available',
      'Correct TDS calibration per model specs',
      'Genuine UV bulbs & RO membranes used',
    ],
    productTypes: [
      { slug: 'ro', name: 'RO', icon: '💧', desc: 'Reverse osmosis purifier' },
      { slug: 'uv', name: 'UV', icon: '☀️', desc: 'Ultraviolet purifier' },
      { slug: 'uf', name: 'UF', icon: '🌊', desc: 'Ultrafiltration purifier' },
      { slug: 'ro_uv', name: 'RO + UV', icon: '💠', desc: 'Combined RO & UV system' },
    ],
    services: [
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New purifier setup & fitting', price: 399 },
      { slug: 'filter_replacement', name: 'Filter Replacement', icon: '🔄', desc: 'Replace complete filter set', price: 799 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'No water / leakage fix', price: 349 },
      { slug: 'amc_service', name: 'AMC Service', icon: '📋', desc: 'Annual maintenance contract', price: 999 },
      { slug: 'membrane_change', name: 'Membrane Change', icon: '♻️', desc: 'RO membrane replacement', price: 849 },
    ],
  },
  {
    key: 'Geyser',
    name: 'Geyser',
    color: '#E65100',
    lightBg: '#FFF3E0',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Regular tank flushing every 2 years extends geyser life significantly.',
    brands: ['Havells', 'AO Smith', 'Racold', 'Bajaj', 'V-Guard', 'Venus', 'Kenstar', 'Usha', 'Orient', 'Crompton'],
    whyBrandPoints: [
      'Brand-specific heating elements & thermostats available',
      'Correct wattage element for your tank capacity',
      'Safety pressure valve check per brand specs',
    ],
    productTypes: [
      { slug: 'storage', name: 'Storage Geyser', icon: '🛢️', desc: '10 L · 15 L · 25 L tank' },
      { slug: 'instant', name: 'Instant Geyser', icon: '⚡', desc: 'Tankless, rapid heating' },
      { slug: 'solar', name: 'Solar Heater', icon: '☀️', desc: 'Solar panel water heater' },
    ],
    services: [
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Heating element & thermostat fix', price: 299 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New geyser fitting & safety check', price: 399 },
      { slug: 'service_flush', name: 'Service & Flush', icon: '✨', desc: 'Tank descaling & flushing', price: 349 },
      { slug: 'element_replacement', name: 'Element Replacement', icon: '🔌', desc: 'Heating rod change', price: 499 },
      { slug: 'anode_replacement', name: 'Anode Rod Change', icon: '🔩', desc: 'Anti-corrosion rod replacement', price: 299 },
    ],
  },
  {
    key: 'Microwave',
    name: 'Microwave',
    color: '#37474F',
    lightBg: '#ECEFF1',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Never use metal containers inside. ServiceProvider will inspect for any magnetron damage.',
    brands: ['LG', 'Samsung', 'IFB', 'Morphy Richards', 'Bajaj', 'Panasonic', 'Godrej', 'Whirlpool', 'Philips', 'Bosch'],
    whyBrandPoints: [
      'Brand-specific magnetron & waveguide cover parts',
      'Correct turntable motor & coupler replacements',
      'Model-specific control panel & keypad parts',
    ],
    productTypes: [
      { slug: 'solo', name: 'Solo Microwave', icon: '📡', desc: 'Basic reheating only' },
      { slug: 'grill', name: 'Grill Microwave', icon: '🔥', desc: 'Heating + grilling mode' },
      { slug: 'convection', name: 'Convection', icon: '🌀', desc: 'Baking, roasting & grilling' },
      { slug: 'otg', name: 'OTG', icon: '🍞', desc: 'Oven toaster griller' },
    ],
    services: [
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Not heating, sparking or dead', price: 349 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'Setup, demo & safety check', price: 199 },
      { slug: 'deep_cleaning', name: 'Deep Cleaning', icon: '✨', desc: 'Interior deodorisation & clean', price: 249 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Annual check & magnetron test', price: 299 },
    ],
  },
  {
    key: 'Chimney',
    name: 'Chimney',
    color: '#212121',
    lightBg: '#F5F5F5',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Chimney should be deep-cleaned every 3–6 months for optimal suction performance.',
    brands: ['Faber', 'Elica', 'Glen', 'Hindware', 'Kaff', 'Sunflame', 'Bosch', 'IFB', 'Siemens', 'Whirlpool'],
    whyBrandPoints: [
      'Brand-specific motor & oil collector parts available',
      'Correct ducting adaptor & pipe fittings used',
      'Auto-clean motor serviced per brand manual',
    ],
    productTypes: [
      { slug: 'baffle', name: 'Baffle Filter', icon: '🌀', desc: 'Curved aluminium mesh' },
      { slug: 'cassette', name: 'Cassette Filter', icon: '📦', desc: 'Easy-clean cartridge' },
      { slug: 'auto', name: 'Auto-Clean', icon: '✨', desc: 'Self-cleaning oil collector' },
      { slug: 'filterless', name: 'Filterless', icon: '🔆', desc: 'No filter, centrifugal tech' },
    ],
    services: [
      { slug: 'deep_cleaning', name: 'Deep Cleaning', icon: '✨', desc: 'Filter, motor & oil collector clean', price: 399 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Motor, suction & button fix', price: 349 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'New chimney mounting & ducting', price: 499 },
      { slug: 'filter_replace', name: 'Filter Replacement', icon: '🔄', desc: 'Baffle / mesh / cassette change', price: 299 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Annual service & suction test', price: 349 },
    ],
  },
  {
    key: 'Air Cooler',
    name: 'Air Cooler',
    color: '#1565C0',
    lightBg: '#E3F2FD',
    groups: ['appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Replace cooling pads every season for best cooling efficiency.',
    brands: ['Symphony', 'Bajaj', 'Orient', 'Kenstar', 'Crompton', 'Hindware', 'Usha', 'Havells', 'Voltas', 'Cello'],
    whyBrandPoints: [
      'Brand-specific pump & motor replacements available',
      'Correct cooling pad type (honeycomb vs wood wool)',
      'Float valve & water distributor parts matched to model',
    ],
    productTypes: [
      { slug: 'desert', name: 'Desert Cooler', icon: '🏜️', desc: 'Large, high-capacity tank' },
      { slug: 'personal', name: 'Personal Cooler', icon: '👤', desc: 'Compact & portable' },
      { slug: 'tower', name: 'Tower Cooler', icon: '🏛️', desc: 'Tall, 360° airflow' },
      { slug: 'window', name: 'Window Cooler', icon: '🪟', desc: 'Window-mounted unit' },
    ],
    services: [
      { slug: 'service_clean', name: 'Service & Clean', icon: '✨', desc: 'Pad, pump & tank clean', price: 249 },
      { slug: 'repair', name: 'Repair', icon: '🔧', desc: 'Motor, pump & fan fix', price: 299 },
      { slug: 'installation', name: 'Installation', icon: '🔩', desc: 'Setup & positioning', price: 199 },
      { slug: 'pad_change', name: 'Cooling Pad Change', icon: '🧽', desc: 'Replace honeycomb/wood pads', price: 349 },
      { slug: 'maintenance', name: 'Maintenance', icon: '🛠️', desc: 'Pre-summer full check', price: 299 },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // GENERAL HANDYMAN SERVICES (non-appliance) — ported 1:1 from the prices
  // and descriptions frontend/src/pages/ServiceDetails.jsx's CARPENTER_CATALOG,
  // PLUMBER_CATALOG and ELECTRICIAN_CATALOG constants already showed
  // customers, so this migration doesn't change a single number anyone has
  // already seen — it just makes those numbers a real, admin-editable row
  // instead of a value baked into the frontend bundle.
  // ────────────────────────────────────────────────────────────────────────
  {
    key: 'Electrician',
    name: 'Electrician',
    color: '#F9A825',
    lightBg: '#FFFDE7',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'Prices shown are indicative. The electrician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Electrician Consultancy', icon: '🔍', desc: 'Not sure where to start? Book a consultation to diagnose tripping or wiring. Consultation fee adjusted against final service invoice.', price: 149 },
      { slug: 'socket_switchboard', name: 'Socket & Switchboard Repair/Installation', icon: '🔌', desc: 'Switchboard installation, modular socket repair & replacement. Safe, spark-free testing with genuine parts.', price: 199 },
      { slug: 'fan_installation', name: 'Fan Installation & Repair', icon: '🌀', desc: 'Ceiling fan, exhaust fan, and wall fan installation. Fan repair including capacitor replacement and blade alignment.', price: 249 },
      { slug: 'wiring_repair', name: 'Wiring & Short Circuit Repair', icon: '⚡', desc: 'Diagnose and fix faulty wiring, trips, and short circuits. Safe, insulated tools and certified electricians.', price: 399 },
      { slug: 'mcb_db_repair', name: 'MCB / DB Box Repair', icon: '🛠️', desc: 'MCB replacement and distribution box servicing. All ratings (6A to 63A) supported with genuine ISI parts.', price: 349 },
    ],
  },
  {
    key: 'Carpenter',
    name: 'Carpenter',
    color: '#795548',
    lightBg: '#EFEBE9',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'Prices shown are indicative. The carpenter will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Carpentry Consultation & Inspection', icon: '🔍', desc: 'Expert carpenter inspection for custom furniture, woodwork repair, or mounting. Consultation fee adjusted against final service invoice.', price: 149 },
      { slug: 'bed_wardrobe', name: 'Bed & Wardrobe Assembly / Repair', icon: '🛏️', desc: 'Assembly and dismantle of king, queen, or single beds and wardrobes. Hinge adjustment, door alignment, and tight fitting.', price: 449 },
      { slug: 'table_chair', name: 'Table & Chair Repair', icon: '🪑', desc: 'Fix loose wooden legs, wobbly dining chairs, and squeaky joints. High-strength adhesive and industrial screws included.', price: 249 },
      { slug: 'door_lock', name: 'Door Lock Installation & Repair', icon: '🔐', desc: 'Installation of mortise lock, handle set, cylindrical lock, or latch fix. Ensures smooth latching and deadbolt alignment.', price: 299 },
      { slug: 'window_mesh', name: 'Window & Mesh Fitting', icon: '🪟', desc: 'Fix sliding window channels, wooden shutters, and mosquito mesh. Smooth gliding guaranteed.', price: 199 },
      { slug: 'wall_hanging', name: 'Wall Hangings & Mirror Mounting', icon: '🖼️', desc: 'Drill and hang wall art, mirrors, clocks, bathroom accessories, and shelves. Clean, precise drilling with zero wall chipping.', price: 149 },
    ],
  },
  {
    key: 'Plumber',
    name: 'Plumber',
    color: '#1976D2',
    lightBg: '#E3F2FD',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'Prices shown are indicative. The plumber will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Plumber Inspection & Diagnosis', icon: '🔍', desc: 'Complete diagnosis for concealed leakage, low water pressure, and pipe issues. Inspection charge waived off on repair.', price: 149 },
      { slug: 'tap_mixer', name: 'Tap & Mixer Repair / Replacement', icon: '🚰', desc: 'Fix continuous dripping, spindle replacement, and angle valve installation. Compatible with Jaguar, Kohler, Hindware, and all major brands.', price: 199 },
      { slug: 'shower_diverter', name: 'Shower & Diverter Servicing', icon: '🚿', desc: 'Unclog shower nozzles, fix diverter cartridge, and clean hard water deposits.', price: 299 },
      { slug: 'drainage', name: 'Drainage Blockage Clearing', icon: '🌊', desc: 'Unclog kitchen sink, bathroom floor trap, and balcony drainage. High-pressure rotary snake tool used for deep clearance.', price: 299 },
      { slug: 'pipeline_leak', name: 'Pipeline Leakage Repair', icon: '🔧', desc: 'Repair damaged CPVC/UPVC pipes and solvent joint sealing.', price: 349 },
    ],
  },
  {
    key: 'Sofa Repair',
    name: 'Sofa Repair',
    color: '#6D4C41',
    lightBg: '#EFEBE9',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Sofa Repair Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for sofa repair by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Sofa Repair Service', icon: '🛋️', desc: 'Comprehensive repair, servicing, and inspection for your sofa. Includes genuine replacement parts and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'Tile Grouting',
    name: 'Tile Grouting',
    color: '#546E7A',
    lightBg: '#ECEFF1',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Tile Grouting Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for tile grouting by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Tile Grouting Service', icon: '🧱', desc: 'Comprehensive re-grouting, sealing, and inspection for your tiles. Includes genuine materials and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'Furniture Assembly',
    name: 'Furniture Assembly',
    color: '#8D6E63',
    lightBg: '#EFEBE9',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Furniture Assembly Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for furniture assembly by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Furniture Assembly Service', icon: '🪑', desc: 'Comprehensive assembly, fitting, and inspection for your furniture. Includes genuine hardware and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'TV Installation',
    name: 'TV Installation',
    color: '#B71C1C',
    lightBg: '#FFEBEE',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'TV Installation Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for TV installation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard TV Installation Service', icon: '📺', desc: 'Wall mounting, alignment, and cable management for your TV. Includes genuine mounting hardware and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'Hanger Installation',
    name: 'Hanger Installation',
    color: '#00838F',
    lightBg: '#E0F7FA',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Hanger Installation Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for hanger installation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Hanger Installation Service', icon: '🪝', desc: 'Comprehensive installation and inspection for cloth hangers / drying stands. Includes genuine hardware and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'Mosquito Mesh',
    name: 'Mosquito Mesh',
    color: '#2E7D32',
    lightBg: '#E8F5E9',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Mosquito Mesh Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for mosquito mesh fitting by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Mosquito Mesh Service', icon: '🦟', desc: 'Comprehensive mesh fitting, frame alignment, and inspection. Includes genuine materials and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'Safety Net',
    name: 'Safety Net',
    color: '#455A64',
    lightBg: '#ECEFF1',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Safety Net Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for balcony/window safety nets by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Safety Net Service', icon: '🕸️', desc: 'Comprehensive net installation, anchoring, and inspection. Includes genuine materials and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'Gas Stove & Hob Services',
    name: 'Gas Stove & Hob Services',
    color: '#EF6C00',
    lightBg: '#FFF3E0',
    groups: ['handyman'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Gas Stove Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for gas stove/hob by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Gas Stove Service', icon: '🔥', desc: 'Comprehensive repair, servicing, and inspection for your gas stove or hob. Includes genuine replacement parts and workmanship warranty.', price: 299 },
    ],
  },
  {
    key: 'Gas Pipeline Installation',
    name: 'Gas Pipeline Installation',
    color: '#D84315',
    lightBg: '#FBE9E7',
    groups: ['handyman'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Gas Pipeline Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for gas pipeline installation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Gas Pipeline Installation', icon: '🛠️', desc: 'Comprehensive pipeline fitting, leak testing, and safety certification. Includes genuine materials and workmanship warranty.', price: 499 },
    ],
  },
  {
    key: 'Full House Cleaning',
    name: 'Full house cleaning',
    color: '#00897B',
    lightBg: '#E0F2F1',
    groups: ['handyman', 'cleaning'],
    section: 'Cleaning',
    categoryNote: 'Hospital-grade eco-friendly chemicals used on every visit.',
    productTypes: [],
    services: [
      { slug: 'full_home_deep_clean', name: 'Complete Full Home Deep Cleaning', icon: '✨', desc: 'Deep scrubbing and sanitization of bedrooms, living room, balconies, and windows. Hospital-grade eco-friendly chemicals used.', price: 2499, unit: 'per home' },
    ],
  },
  {
    key: 'Bathroom Cleaning',
    name: 'Bathroom cleaning',
    color: '#0097A7',
    lightBg: '#E0F7FA',
    groups: ['handyman', 'cleaning'],
    section: 'Cleaning',
    categoryNote: 'Hospital-grade eco-friendly chemicals used on every visit.',
    productTypes: [],
    services: [
      { slug: 'bathroom_deep_clean', name: 'Bathroom Deep Cleaning', icon: '🚿', desc: 'Tile stain removal, hard water descaling, mirror shine, and toilet bowl sanitization.', price: 449, unit: 'per bathroom' },
    ],
  },
  {
    key: 'Kitchen Cleaning',
    name: 'Kitchen Cleaning',
    color: '#43A047',
    lightBg: '#E8F5E9',
    groups: ['handyman', 'cleaning'],
    section: 'Cleaning',
    categoryNote: 'Hospital-grade eco-friendly chemicals used on every visit.',
    productTypes: [],
    services: [
      { slug: 'kitchen_deep_clean', name: 'Kitchen Deep Cleaning', icon: '✨', desc: 'Oil and grease removal from slab, tiles, stove, and chimney exteriors.', price: 899, unit: 'per kitchen' },
    ],
  },
  {
    key: 'Sofa Carpet Mattress Cleaning',
    name: 'Sofa, Carpet & Mattress Cleaning',
    color: '#6A1B9A',
    lightBg: '#F3E5F5',
    groups: ['cleaning'],
    section: 'Cleaning',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Sofa/Carpet/Mattress Cleaning Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for upholstery cleaning by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Upholstery Deep Clean', icon: '🛋️', desc: 'Vacuum extraction, stain treatment, and sanitization for sofas, carpets, and mattresses.', price: 299 },
    ],
  },
  {
    key: 'Water Tank Sump Cleaning',
    name: 'Water Tank & Sump Cleaning',
    color: '#0277BD',
    lightBg: '#E1F5FE',
    groups: ['cleaning'],
    section: 'Cleaning',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Water Tank Cleaning Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for water tank/sump cleaning by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Tank & Sump Cleaning', icon: '💧', desc: 'Draining, scrubbing, and sanitization of overhead tanks and underground sumps.', price: 299 },
    ],
  },
  {
    key: 'Marble Polishing',
    name: 'Marble Polishing',
    color: '#78909C',
    lightBg: '#ECEFF1',
    groups: ['cleaning'],
    section: 'Cleaning',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Marble Polishing Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for marble flooring by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Marble Polishing Service', icon: '✨', desc: 'Diamond grinding, crystallization, and high-gloss polishing for marble floors.', price: 299 },
    ],
  },
  {
    key: 'Pest Control',
    name: 'Pest control',
    color: '#558B2F',
    lightBg: '#F1F8E9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Pest Control Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for general pest infestation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard General Pest Control', icon: '🐜', desc: 'Comprehensive spraying, gel treatment, and inspection for common household pests.', price: 299 },
    ],
  },
  {
    key: 'Cockroach Control Treatment',
    name: 'Cockroach Control Treatment',
    color: '#4E342E',
    lightBg: '#EFEBE9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Cockroach Control Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for cockroach infestation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Cockroach Control Treatment', icon: '🪳', desc: 'Gel-based and spray treatment targeting cockroach breeding zones.', price: 299 },
    ],
  },
  {
    key: 'Bed Bug Control Treatment',
    name: 'Bed Bug Control Treatment',
    color: '#AD1457',
    lightBg: '#FCE4EC',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Bed Bug Control Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for bed bug infestation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Bed Bug Control Treatment', icon: '🛏️', desc: 'Heat and spray treatment for mattresses, bed frames, and upholstery.', price: 299 },
    ],
  },
  {
    key: 'Rodent Control Treatment',
    name: 'Rodent Control Treatment',
    color: '#5D4037',
    lightBg: '#EFEBE9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Rodent Control Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for rodent infestation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Rodent Control Treatment', icon: '🐭', desc: 'Trap placement and baiting treatment for rodent-proofing your home.', price: 299 },
    ],
  },
  {
    key: 'Termite Control',
    name: 'Termite Control',
    color: '#6D4C41',
    lightBg: '#EFEBE9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Termite Control Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for termite infestation by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Termite Control Treatment', icon: '🐛', desc: 'Anti-termite chemical barrier and wood treatment for long-term protection.', price: 299 },
    ],
  },
  {
    key: 'Wall Painting',
    name: 'Wall Painting',
    color: '#F4511E',
    lightBg: '#FBE9E7',
    groups: ['handyman', 'cleaning', 'painting'],
    section: 'Painting & Water proofing',
    categoryNote: 'Prices shown are indicative. The painter will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Wall Painting Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and estimate for interior/exterior wall painting by certified painters. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Wall Painting Service', icon: '🎨', desc: 'Surface prep, primer, and two coats of premium emulsion paint.', price: 299, unit: 'per room' },
    ],
  },
  {
    key: 'Waterproofing',
    name: 'Waterproofing',
    color: '#0288D1',
    lightBg: '#E1F5FE',
    groups: ['handyman', 'cleaning', 'painting'],
    section: 'Painting & Water proofing',
    categoryNote: 'Prices shown are indicative. The technician will confirm exact charges after inspection.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Waterproofing Consultation & Checkup', icon: '🔍', desc: 'Expert inspection and diagnosis for leakage and seepage by certified technicians. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Waterproofing Service', icon: '💧', desc: 'Crack sealing and waterproof membrane coating for terraces, walls, and bathrooms.', price: 499, unit: 'per area' },
    ],
  },
  {
    key: 'Home Shifting',
    name: 'Home Shifting',
    color: '#F9A825',
    lightBg: '#FFFDE7',
    groups: ['movers'],
    section: 'Movers & Storage',
    categoryNote: 'Prices shown are indicative. Final quote depends on distance and load.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Home Shifting Consultation & Checkup', icon: '🔍', desc: 'Expert survey and estimate for household relocation by certified movers. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Home Shifting Service', icon: '📦', desc: 'Packing, loading, transport, and unloading for a full household move.', price: 2999, unit: 'per move' },
    ],
  },
  {
    key: 'Office Relocation',
    name: 'Office Relocation',
    color: '#5E35B1',
    lightBg: '#EDE7F6',
    groups: ['movers'],
    section: 'Movers & Storage',
    categoryNote: 'Prices shown are indicative. Final quote depends on distance and load.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Office Relocation Consultation & Checkup', icon: '🔍', desc: 'Expert survey and estimate for office relocation by certified movers. Consultation charge is adjusted against your final service invoice.', price: 149 },
      { slug: 'standard_service', name: 'Standard Office Relocation Service', icon: '🏢', desc: 'Packing, loading, transport, and unloading for office furniture and equipment.', price: 3999, unit: 'per move' },
    ],
  },
  {
    key: 'Home Renovation',
    name: 'Home Renovation',
    color: '#00695C',
    lightBg: '#E0F2F1',
    groups: ['renovation'],
    section: 'Renovation',
    categoryNote: 'Prices shown are indicative. Final quote depends on scope of work.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Home Renovation Consultation & Checkup', icon: '🔍', desc: 'On-site survey and estimate for full home renovation by certified contractors. Consultation charge is adjusted against your final service invoice.', price: 299 },
      { slug: 'standard_service', name: 'Standard Home Renovation Service', icon: '🏠', desc: 'Civil work, painting, and fixture upgrades scoped after inspection.', price: 4999, unit: 'per project' },
    ],
  },
  {
    key: 'Kitchen Renovation',
    name: 'Kitchen Renovation',
    color: '#EF6C00',
    lightBg: '#FFF3E0',
    groups: ['renovation'],
    section: 'Renovation',
    categoryNote: 'Prices shown are indicative. Final quote depends on scope of work.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Kitchen Renovation Consultation & Checkup', icon: '🔍', desc: 'On-site survey and estimate for kitchen renovation by certified contractors. Consultation charge is adjusted against your final service invoice.', price: 299 },
      { slug: 'standard_service', name: 'Standard Kitchen Renovation Service', icon: '🍳', desc: 'Modular fittings, tiling, and plumbing/electrical rework scoped after inspection.', price: 3999, unit: 'per project' },
    ],
  },
  {
    key: 'Bathroom Renovation',
    name: 'Bathroom Renovation',
    color: '#00838F',
    lightBg: '#E0F7FA',
    groups: ['renovation'],
    section: 'Renovation',
    categoryNote: 'Prices shown are indicative. Final quote depends on scope of work.',
    productTypes: [],
    services: [
      { slug: 'consultation', name: 'Bathroom Renovation Consultation & Checkup', icon: '🔍', desc: 'On-site survey and estimate for bathroom renovation by certified contractors. Consultation charge is adjusted against your final service invoice.', price: 299 },
      { slug: 'standard_service', name: 'Standard Bathroom Renovation Service', icon: '🚽', desc: 'Fittings, tiling, and waterproofing rework scoped after inspection.', price: 3499, unit: 'per project' },
    ],
  },
];
