// Service categories: key, name, visuals, grouping and booking-flow
// copy. Deliberately no product types, services or prices — those live only
// in the Master Catalogue (masterCatalogueSeedData.js, docs/master-catalogue).
export const CATEGORY_SEED = [
  {
    key: 'AC',
    name: 'AC',
    color: '#0D47A1',
    lightBg: '#EAF4FF',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
    whyBrandPoints: [
      'ServiceProviders carry brand-specific gas & parts',
      'AC model-specific calibration & settings',
      'Correct refrigerant type (R22 vs R410A)',
    ],
  },
  {
    key: 'Washing Machine',
    name: 'Washing Machine',
    color: '#1565C0',
    lightBg: '#E3F2FD',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
    whyBrandPoints: [
      'Brand-specific PCB & motor spare parts stocked',
      'Correct drum belt & bearing specifications',
      'Model-specific error code diagnosis',
    ],
  },
  {
    key: 'Refrigerator',
    name: 'Refrigerator',
    color: '#4527A0',
    lightBg: '#EDE7F6',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Cooling issues may need gas refilling — exact diagnosis done by the serviceProvider on-site.',
    whyBrandPoints: [
      'Brand-specific compressor & thermostat parts',
      'Correct refrigerant type (R600a vs R134a)',
      'Model-specific PCB & sensor calibration',
    ],
  },
  {
    key: 'TV',
    name: 'TV',
    color: '#B71C1C',
    lightBg: '#FFEBEE',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Panel repairs depend on part availability. ServiceProvider will confirm before proceeding.',
    whyBrandPoints: [
      'Brand-specific display panels & backlights stocked',
      'Firmware & software issues diagnosed correctly',
      'Correct T-Con board & power supply components',
    ],
  },
  {
    key: 'RO Water Purifier',
    name: 'RO Water Purifier',
    color: '#00695C',
    lightBg: '#E0F2F1',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Filter replacement intervals depend on your water quality (usually every 6–12 months).',
    whyBrandPoints: [
      'Brand-specific filter cartridges & membranes available',
      'Correct TDS calibration per model specs',
      'Genuine UV bulbs & RO membranes used',
    ],
  },
  {
    key: 'Geyser',
    name: 'Geyser',
    color: '#E65100',
    lightBg: '#FFF3E0',
    groups: ['handyman', 'appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Regular tank flushing every 2 years extends geyser life significantly.',
    whyBrandPoints: [
      'Brand-specific heating elements & thermostats available',
      'Correct wattage element for your tank capacity',
      'Safety pressure valve check per brand specs',
    ],
  },
  {
    key: 'Microwave',
    name: 'Microwave',
    color: '#37474F',
    lightBg: '#ECEFF1',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Never use metal containers inside. ServiceProvider will inspect for any magnetron damage.',
    whyBrandPoints: [
      'Brand-specific magnetron & waveguide cover parts',
      'Correct turntable motor & coupler replacements',
      'Model-specific control panel & keypad parts',
    ],
  },
  {
    key: 'Chimney',
    name: 'Chimney',
    color: '#212121',
    lightBg: '#F5F5F5',
    groups: ['handyman', 'appliance'],
    section: 'Kitchen and Appliance',
    categoryNote: 'Chimney should be deep-cleaned every 3–6 months for optimal suction performance.',
    whyBrandPoints: [
      'Brand-specific motor & oil collector parts available',
      'Correct ducting adaptor & pipe fittings used',
      'Auto-clean motor serviced per brand manual',
    ],
  },
  {
    key: 'Air Cooler',
    name: 'Air Cooler',
    color: '#1565C0',
    lightBg: '#E3F2FD',
    groups: ['appliance'],
    section: 'AC & Appliance Repair',
    categoryNote: 'Replace cooling pads every season for best cooling efficiency.',
    whyBrandPoints: [
      'Brand-specific pump & motor replacements available',
      'Correct cooling pad type (honeycomb vs wood wool)',
      'Float valve & water distributor parts matched to model',
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // GENERAL HANDYMAN SERVICES (non-appliance) — ported 1:1 from the prices
  // and descriptions frontend/src/pages/ServiceDetails.jsx's CARPENTER_CATALOG,
  // PLUMBER_CATALOG and ELECTRICIAN_CATALOG constants already showed
  // customers, so this migration doesn't change a single number anyone has
  // already seen — it just makes those numbers a real, admin-editable row
  // instead of a value baked into the frontend bundle.
  // ────────────────────────────────────────────────────────────────────────
  {
    key: 'Electrician',
    name: 'Electrician',
    color: '#F9A825',
    lightBg: '#FFFDE7',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Carpenter',
    name: 'Carpenter',
    color: '#795548',
    lightBg: '#EFEBE9',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Plumber',
    name: 'Plumber',
    color: '#1976D2',
    lightBg: '#E3F2FD',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Sofa Repair',
    name: 'Sofa Repair',
    color: '#6D4C41',
    lightBg: '#EFEBE9',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Tile Grouting',
    name: 'Tile Grouting',
    color: '#546E7A',
    lightBg: '#ECEFF1',
    groups: ['handyman'],
    section: 'Maintenance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Furniture Assembly',
    name: 'Furniture Assembly',
    color: '#8D6E63',
    lightBg: '#EFEBE9',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'TV Installation',
    name: 'TV Installation',
    color: '#B71C1C',
    lightBg: '#FFEBEE',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
    // Duplicate of TV → Installation in the Master Catalogue; hidden so search
    // and the category grid show one TV installation, priced by screen size.
    isActive: false,
  },
  {
    key: 'Hanger Installation',
    name: 'Hanger Installation',
    color: '#00838F',
    lightBg: '#E0F7FA',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Mosquito Mesh',
    name: 'Mosquito Mesh',
    color: '#2E7D32',
    lightBg: '#E8F5E9',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Safety Net',
    name: 'Safety Net',
    color: '#455A64',
    lightBg: '#ECEFF1',
    groups: ['handyman'],
    section: 'Installation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Gas Stove & Hob Services',
    name: 'Gas Stove & Hob Services',
    color: '#EF6C00',
    lightBg: '#FFF3E0',
    groups: ['handyman'],
    section: 'Kitchen and Appliance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Gas Pipeline Installation',
    name: 'Gas Pipeline Installation',
    color: '#D84315',
    lightBg: '#FBE9E7',
    groups: ['handyman'],
    section: 'Kitchen and Appliance',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Full House Cleaning',
    name: 'Full house cleaning',
    color: '#00897B',
    lightBg: '#E0F2F1',
    groups: ['handyman', 'cleaning'],
    section: 'Cleaning',
    categoryNote: 'Hospital-grade eco-friendly chemicals used on every visit.',
  },
  {
    key: 'Bathroom Cleaning',
    name: 'Bathroom cleaning',
    color: '#0097A7',
    lightBg: '#E0F7FA',
    groups: ['handyman', 'cleaning'],
    section: 'Cleaning',
    categoryNote: 'Hospital-grade eco-friendly chemicals used on every visit.',
  },
  {
    key: 'Kitchen Cleaning',
    name: 'Kitchen Cleaning',
    color: '#43A047',
    lightBg: '#E8F5E9',
    groups: ['handyman', 'cleaning'],
    section: 'Cleaning',
    categoryNote: 'Hospital-grade eco-friendly chemicals used on every visit.',
  },
  {
    key: 'Sofa Carpet Mattress Cleaning',
    name: 'Sofa, Carpet & Mattress Cleaning',
    color: '#6A1B9A',
    lightBg: '#F3E5F5',
    groups: ['cleaning'],
    section: 'Cleaning',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Water Tank Sump Cleaning',
    name: 'Water Tank & Sump Cleaning',
    color: '#0277BD',
    lightBg: '#E1F5FE',
    groups: ['cleaning'],
    section: 'Cleaning',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Marble Polishing',
    name: 'Marble Polishing',
    color: '#78909C',
    lightBg: '#ECEFF1',
    groups: ['cleaning'],
    section: 'Cleaning',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Pest Control',
    name: 'Pest control',
    color: '#558B2F',
    lightBg: '#F1F8E9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Cockroach Control Treatment',
    name: 'Cockroach Control Treatment',
    color: '#4E342E',
    lightBg: '#EFEBE9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Bed Bug Control Treatment',
    name: 'Bed Bug Control Treatment',
    color: '#AD1457',
    lightBg: '#FCE4EC',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Rodent Control Treatment',
    name: 'Rodent Control Treatment',
    color: '#5D4037',
    lightBg: '#EFEBE9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Termite Control',
    name: 'Termite Control',
    color: '#6D4C41',
    lightBg: '#EFEBE9',
    groups: ['cleaning'],
    section: 'Pest Control',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Wall Painting',
    name: 'Wall Painting',
    color: '#F4511E',
    lightBg: '#FBE9E7',
    groups: ['handyman', 'cleaning', 'painting'],
    section: 'Painting & Water proofing',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Waterproofing',
    name: 'Waterproofing',
    color: '#0288D1',
    lightBg: '#E1F5FE',
    groups: ['handyman', 'cleaning', 'painting'],
    section: 'Painting & Water proofing',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Home Shifting',
    name: 'Home Shifting',
    color: '#F9A825',
    lightBg: '#FFFDE7',
    groups: ['movers'],
    section: 'Movers & Storage',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Office Relocation',
    name: 'Office Relocation',
    color: '#5E35B1',
    lightBg: '#EDE7F6',
    groups: ['movers'],
    section: 'Movers & Storage',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Home Renovation',
    name: 'Home Renovation',
    color: '#00695C',
    lightBg: '#E0F2F1',
    groups: ['renovation'],
    section: 'Renovation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Kitchen Renovation',
    name: 'Kitchen Renovation',
    color: '#EF6C00',
    lightBg: '#FFF3E0',
    groups: ['renovation'],
    section: 'Renovation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
  {
    key: 'Bathroom Renovation',
    name: 'Bathroom Renovation',
    color: '#00838F',
    lightBg: '#E0F7FA',
    groups: ['renovation'],
    section: 'Renovation',
    categoryNote: 'The price you confirm is what you pay for the service. Spare parts, if needed, are quoted separately for your approval.',
  },
];
