// Shared Mongoose schema plugins so every model gets the same conventions
// without repeating boilerplate: a human-readable ID field (generated by
// idGenerator in a pre-save hook, wired up alongside the first module that
// needs it) and consistent toJSON shaping (_id -> id, drop __v).

export function humanIdPlugin(schema, { prefix, field = 'humanId' }) {
  schema.add({ [field]: { type: String, unique: true, sparse: true, index: true } });
  schema.statics.humanIdPrefix = prefix;
}

export function toJSONPlugin(schema) {
  schema.set('toJSON', {
    virtuals: true,
    versionKey: false,
    transform: (_doc, ret) => {
      ret.id = ret._id;
      delete ret._id;
      return ret;
    },
  });
}

export function applyStandardPlugins(schema, opts = {}) {
  toJSONPlugin(schema);
  if (opts.prefix) humanIdPlugin(schema, opts);
  return schema;
}
