// Shared Mongoose schema plugins so every model gets the same conventions
// without repeating boilerplate: a human-readable ID field (generated by
// idGenerator in a pre-save hook) and consistent toJSON shaping (_id -> id,
// drop __v).

import { generateHumanId } from './idGenerator.js';

export function humanIdPlugin(schema, { prefix, field = 'humanId' }) {
  schema.add({ [field]: { type: String, unique: true, sparse: true, index: true } });
  schema.statics.humanIdPrefix = prefix;

  schema.pre('save', async function assignHumanId() {
    if (this.isNew && !this[field]) {
      this[field] = await generateHumanId(prefix);
    }
  });
}

export function toJSONPlugin(schema) {
  schema.set('toJSON', {
    virtuals: true,
    versionKey: false,
    transform: (_doc, ret) => {
      ret.id = ret._id;
      delete ret._id;
      return ret;
    },
  });
}

export function applyStandardPlugins(schema, opts = {}) {
  toJSONPlugin(schema);
  if (opts.prefix) humanIdPlugin(schema, opts);
  return schema;
}
